### ISSUE TITLE
New error on train, possibly caused by beam-search-decoder bugfix

### ISSUE THREAD

**Issue by lk251** [DongjunLee/conversation-tensorflow#10]
when running

 python main.py --config cornell-movie-dialogs --mode train_and_evaluate

I get the error message

> load vocab ...
> vocab size: 41676
> make Training data and Test data Start....
> 196665it [00:07, 26114.28it/s]
> load data from train_ids.enc, train_ids.dec...
> 25009it [00:00, 27803.06it/s]
> load data from test_ids.enc, test_ids.dec...
> train data count : 89711
> test data count : 11324
> shuffle dataset ...
> sorted by inputs length and outputs length ...
> WARNING:tensorflow:RunConfig.uid (from tensorflow.contrib.learn.python.learn.estimators.run_config) is experimental and may change or be removed at any time, and without warning.
> Traceback (most recent call last):
>   File "main.py", line 99, in <module>
>     main(args.mode)
>   File "main.py", line 72, in main
>     hparams=params
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
>     return _execute_schedule(experiment, schedule)
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
>     return task()
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
>     hooks=self._train_monitors + extra_hooks)
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
>     hooks=hooks)
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
>     loss = self._train_model(input_fn, hooks, saving_listeners)
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
>     features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
>   File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
>     model_fn_results = self._model_fn(features=features, **kwargs)
>   File "/home/ubuntu/conversation-tensorflow/model.py", line 23, in model_fn
>     self.build_graph()
>   File "/home/ubuntu/conversation-tensorflow/model.py", line 57, in build_graph
>     decoder_inputs=self.decoder_inputs)
>   File "/home/ubuntu/conversation-tensorflow/seq2seq_attention/__init__.py", line 37, in build
>     self._build_decoder()
>   File "/home/ubuntu/conversation-tensorflow/seq2seq_attention/__init__.py", line 115, in _build_decoder
>     self.decoder_logits = decoder_outputs.rnn_output
> AttributeError: 'tuple' object has no attribute 'rnn_output'
> The learning is finished with *conversation-tensorflow* Project using `cornell-movie-dialogs` config.

This didn't happen before, so it's likely associated with the fixes for #9

**Comment by DongjunLee** [comment]
oh, I'll check it. thank you for issuing.

**Comment by lk251** [comment]
Thank you!

**Comment by scotwilli** [comment]
Even Iam also getting same error.

**Comment by DongjunLee** [comment]
I fixed it. :) 
pull and try again.
