### ISSUE TITLE
ValueError: Expected state to be a tuple of length 1, but received: Tensor("decoder/decoder/while/Identity_3:0", shape=(?, 1024), dtype=float32)

### ISSUE THREAD

**Issue by JacomusP** [DongjunLee/conversation-tensorflow#14]
I'm just trying to train the model on my own dataset and I keep getting this error:

Traceback (most recent call last):
  File "train.py", line 95, in <module>
    main(args.mode)
  File "train.py", line 72, in main
    hparams=params
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 218, in run
    return _execute_schedule(experiment, schedule)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/learn_runner.py", line 46, in _execute_schedule
    return task()
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 367, in train
    hooks=self._train_monitors + extra_hooks)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/experiment.py", line 807, in _call_train
    hooks=hooks)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 302, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 711, in _train_model
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/estimator/estimator.py", line 694, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/home/lair06/peterkin/CSE843_FinalProject/model.py", line 19, in model_fn
    self.build_graph()
  File "/home/lair06/peterkin/CSE843_FinalProject/model.py", line 53, in build_graph
    decoder_inputs=self.decoder_inputs)
  File "/home/lair06/peterkin/CSE843_FinalProject/seq2seq_attention/__init__.py", line 33, in build
    self._build_decoder()
  File "/home/lair06/peterkin/CSE843_FinalProject/seq2seq_attention/__init__.py", line 108, in _build_decoder
    length_penalty_weight=Config.predict.length_penalty_weight)
  File "/home/lair06/peterkin/CSE843_FinalProject/seq2seq_attention/decoder.py", line 145, in build
    return self._basic_decoder(helper)
  File "/home/lair06/peterkin/CSE843_FinalProject/seq2seq_attention/decoder.py", line 173, in _basic_decoder
    swap_memory=True)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 286, in dynamic_decode
    swap_memory=swap_memory)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/decoder.py", line 234, in body
    decoder_finished) = decoder.step(time, inputs, state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/basic_decoder.py", line 138, in step
    cell_outputs, cell_state = self._cell(inputs, state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/rnn/python/ops/core_rnn_cell.py", line 230, in call
    output, res_state = self._cell(inputs, state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/contrib/seq2seq/python/ops/attention_wrapper.py", line 1295, in call
    cell_output, next_cell_state = self._cell(cell_inputs, cell_state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 183, in __call__
    return super(RNNCell, self).__call__(inputs, state)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 575, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/home/lair06/anaconda3/envs/tensorflow1.4/lib/python3.6/site-packages/tensorflow/python/ops/rnn_cell_impl.py", line 1060, in call
    (len(self.state_size), state))
ValueError: Expected state to be a tuple of length 1, but received: Tensor("decoder/decoder/while/Identity_3:0", shape=(?, 1024), dtype=float32)

When trying to track down the issue it seems that this problem is in the decoder specifically with setting the initial state. And that's about it. Any ideas what's going wrong?

**Comment by DongjunLee** [comment]
It looks similar with #12.
What is your tensorflow version?

**Comment by JacomusP** [comment]
I'm using Tensorflow version 1.4. And after further research I realized it only produces this error when the encoder is a bidirectional RNN.

And the error in #12 is the error I get when I ran it on Tensorflow 1.7. Have tensorflow 1.7 on my own machine but the machine doing the bulk of the work has tensorflow 1.4 installed.
